export const Province = [
  { id: 1, province: "Province no.1" },
  { id: 2, province: "Madhesh Province" },
  { id: 3, province: "Bagmati Provience" },
  { id: 4, province: "Gandaki Province" },
  { id: 5, province: "Lumbini Province" },
  { id: 6, province: "Karnali Province" },
  { id: 7, province: "Sudurpashchim Province" }
];

export const District = [
  { id: 1, provinceId: 1, district: "Bhojpur" },
  { id: 2, provinceId: 1, district: "Dhankuta" },
  { id: 3, provinceId: 1, district: "Ilam" },
  { id: 4, provinceId: 1, district: "Jhapa" },
  { id: 5, provinceId: 1, district: "Khotang" },
  { id: 6, provinceId: 1, district: "Morang" },
  { id: 7, provinceId: 1, district: "Okhaldhunga" },
  { id: 8, provinceId: 1, district: "Panchthar" },
  { id: 9, provinceId: 1, district: "Sankhuwasabha" },
  { id: 10, provinceId: 1, district: "Solukhumbu" },
  { id: 11, provinceId: 1, district: "Sunsari" },
  { id: 12, provinceId: 1, district: "Taplejung" },
  { id: 13, provinceId: 1, district: "Terhathum" },
  { id: 14, provinceId: 1, district: "Udayapur" },
  { id: 15, provinceId: 2, district: "Gaur" },
  { id: 16, provinceId: 2, district: "Siraha" },
  { id: 17, provinceId: 2, district: "Birgunj" },
  { id: 18, provinceId: 2, district: "Jaleshwor" },
  { id: 19, provinceId: 2, district: "Malangwa" },
  { id: 20, provinceId: 2, district: "Janakpur" },
  { id: 21, provinceId: 2, district: "Rajbiraj" },
  { id: 22, provinceId: 2, district: "Lahan" },
  { id: 23, provinceId: 3, district: "Sindhuli" },
  { id: 24, provinceId: 3, district: "Ramechhap" },
  { id: 25, provinceId: 3, district: "Dolakha" },
  { id: 26, provinceId: 3, district: "Kathmandu" },
  { id: 27, provinceId: 3, district: "Kavrepalanchok" },
  { id: 28, provinceId: 3, district: "Lalitpur" },
  { id: 29, provinceId: 3, district: "Nuwakot" },
  { id: 30, provinceId: 3, district: "Bhaktapur" },
  { id: 31, provinceId: 3, district: "Dhading" },
  { id: 32, provinceId: 3, district: "Rasuwa" },
  { id: 33, provinceId: 3, district: "Sindhupalchok" },
  { id: 34, provinceId: 3, district: "Chitwan" },
  { id: 35, provinceId: 3, district: "Makwanpur" },
  { id: 36, provinceId: 4, district: "Baglung" },
  { id: 37, provinceId: 4, district: "Gorkha" },
  { id: 38, provinceId: 4, district: "Kaski" },
  { id: 39, provinceId: 4, district: "Lamjung" },
  { id: 40, provinceId: 4, district: "Manang" },
  { id: 41, provinceId: 4, district: "Mustang" },
  { id: 42, provinceId: 4, district: "Myagdi" },
  { id: 43, provinceId: 4, district: "Nawalpur" },
  { id: 44, provinceId: 4, district: "Parbat" },
  { id: 45, provinceId: 4, district: "Syangja" },
  { id: 46, provinceId: 4, district: "Tanahun" },
  { id: 47, provinceId: 5, district: "Kapilvastu" },
  { id: 48, provinceId: 5, district: "Parasi" },
  { id: 49, provinceId: 5, district: "Rupandehi" },
  { id: 50, provinceId: 5, district: "Arghakhanchi" },
  { id: 51, provinceId: 5, district: "Gulmi" },
  { id: 52, provinceId: 5, district: "Palpa" },
  { id: 53, provinceId: 5, district: "Dang" },
  { id: 54, provinceId: 5, district: "Pyuthan" },
  { id: 55, provinceId: 5, district: "Rolpa" },
  { id: 56, provinceId: 5, district: "Eastern Rukum" },
  { id: 57, provinceId: 5, district: "Banke" },
  { id: 58, provinceId: 5, district: "Bardiya" },
  { id: 59, provinceId: 6, district: "Western Rukum" },
  { id: 61, provinceId: 6, district: "Salyan" },
  { id: 62, provinceId: 6, district: "Humla" },
  { id: 63, provinceId: 6, district: "Jumla" },
  { id: 64, provinceId: 6, district: "Kalikot" },
  { id: 65, provinceId: 6, district: "Mugu" },
  { id: 66, provinceId: 6, district: "Surkhet" },
  { id: 67, provinceId: 6, district: "Dolpa" },
  { id: 68, provinceId: 6, district: "Dailekh" },
  { id: 69, provinceId: 6, district: "Jajarkot" },
  { id: 70, provinceId: 7, district: "Achham" },
  { id: 71, provinceId: 7, district: "Baitadi" },
  { id: 72, provinceId: 7, district: "Bajhang" },
  { id: 73, provinceId: 7, district: "Bajura" },
  { id: 74, provinceId: 7, district: "Dadeldhura" },
  { id: 75, provinceId: 7, district: "Darchula" },
  { id: 76, provinceId: 7, district: "Doti" },
  { id: 77, provinceId: 7, district: "Kailali" },
  { id: 78, provinceId: 7, district: "Kanchanpur" }
];
